## **Reference ** [Code ](https://colab.research.google.com/drive/1SIegHGZHET3jSV8s2lhesZiP8KaQMc4l#scrollTo=bf79c78b)

# Numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆) `hint: import … as`

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆) `hint: vector is a single raw array`

In [6]:
x  = np.zeros(10)
print(x,'\n',x.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 10


#### 3. How to find the memory size of any array, creat a random 5x6 array and check the sizs (★☆☆)

In [10]:
y = np.random.rand(5,6)
#y
y.size

30

#### 4. How to get the documentation of the numpy add function from the command line? (★☆☆) `hint: use info or ?`

In [153]:
print(np.info(np.add))

np.add?

None


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆) `hint: array[x]`

In [12]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector (single raw array) with values ranging from 10 to 49 (★☆☆) `hint: arange`

In [16]:
s = np.arange(10,50)
print(s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Show how you can Reverse a vector (first element becomes last) (★☆☆)`hint: use index of -1`

In [19]:
y = np.array([1,2,3,4,5])
y[::-1]

array([5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) `hint: use range and reshape!`

In [30]:
a = np.arange(0,9).reshape(3,3)

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) `hint: use the np.nonzero`

In [34]:
k = np.array([1,2,0,0,4,0])

c = np.nonzero(k)

print(c)



(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) `hint: use index and use np.eye`
the following is an example of 5x4 identity matrix


```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

```



In [36]:
x = np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) `hint: np.random.random`

In [38]:
y = np.random.random((3,3,3))
print(y)

[[[0.38170512 0.47188112 0.86157968]
  [0.87676466 0.1583881  0.77798198]
  [0.61318206 0.64933881 0.19415779]]

 [[0.72577311 0.52647796 0.26673948]
  [0.76247342 0.40587829 0.26252314]
  [0.24004767 0.97346359 0.07901567]]

 [[0.66898132 0.16588409 0.26523102]
  [0.05131566 0.10582512 0.01600016]
  [0.74971049 0.1650061  0.6050078 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) `hint: min, max`

In [43]:
Z = np.random.random((10,10))
Z

print('Maximum Value :',np.max(Z),'\n Minimum Value:',np.min(Z))

Maximum Value : 0.9946410874757022 
 Minimum Value: 0.01127289263997977


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) `hint: mean`

In [47]:
q = np.random.random(30)
#q.size

print('Mean Value : ', np.mean(q))

Mean Value :  0.5108492868585863


#### 15. Create a 2d array as following, with 1 on the border and 0 inside.. see generated array (★☆☆)



```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```



In [109]:
# Your code

w =  np.zeros((10,10))
w[0:1,] =1

print(w)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★★☆) `hint: see generated array np.pad   `

In [108]:
# Your code
m =  np.zeros((7,7))
m[1:-1, 1:-1] = 1
print(m)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

 ####18  What is the result of the following expression? (★☆☆) `hint: indexing the nan using np.nan`



```
Z = np.ones((5,5))
Z[0,1]=np.nan
Z
```



In [111]:
"""
First Row Second Element will NAN !!

"""

Z = np.ones((5,5))
Z[0,1]=np.nan
Z

array([[ 1., nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 18. Now, use this expression to find the index of your nan


```
np.argwhere(x!=x)    Hint: x is your array
```





In [117]:
Z = np.ones((5,5))
Z[0,1]=np.nan
print(np.argwhere(Z!=np.nan))

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]


20. Generate the following array 


```
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```



In [124]:
t = np.arange(1,17).reshape(4,4)
print(t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### 19. Extract the following values `array([ 1,  6, 11, 16])`. ` Hint: use np.diagonal()`

In [125]:
n = np.diagonal(t)
print(n)

[ 1  6 11 16]


#### 20. Try to use `np.diag` to Create a 5x5 matrix with diagonal values 11,11,11,11 (★★☆) Hint: use np.diag with k=0 and [11,11,11,11]. -- diag([11,11,11,11],k=-0)

#### 21.  Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) `Hint: use k=-1 when calling np.diag`

In [146]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


####22. Create a 8x8 matrix and fill it with a given pattern (★☆☆) Hint: use np.zeros and do the replace 



```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 23. Use the `np.tile` to generate the same pattern 

```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 24. Generate then Normalize a 5x5 random matrix (★☆☆)  `hint: Normalization_array = (x_arr -mean_value(x))/std_value(x)`

#### 25. generate any 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

where 

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
```
will return

```
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
```




In [138]:
Z = np.arange(11)
# Your code here!. 
x  = -1
Z[4:8] =  Z[4:8]*x
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. Consider an integer vector Z, comment any iligal expressions (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 27. Generate two randon 1D array, How to find common values between two arrays? (★☆☆) `Hint: use intersect1d(Arr1,Arr2)`

In [145]:
Arr1 = np.arange(1,20)
Arr2 = np.arange(0,19)

print(np.intersect1d(Arr1,Arr2))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]




```
# This is formatted as code
```

#### 28. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [140]:
np.seterr(all="ignore")

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

####29. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [139]:
np.sqrt(-1) == np.emath.sqrt(-1)

#False 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False